apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbos-gitops-volumes
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    gitops.tier.layer: rio-applications
spec:
  destination:
    namespace: doc
    server: https://kubernetes.default.svc
  project: doc-project
  source:
    path: db-gene-demo-capacity-planning/dbos-volumes-3.2.0-SG # repoURL and revision added in the Kustomization file
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
