apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    gitops.tier.layer: gitops
spec:
  destination:
    namespace: doc
    server: https://kubernetes.default.svc
  project: doc-project
  source: # repoURL  and targetRevision populated by kustomize patches in single-cluster/kustomization.yaml
    path: 0-bootstrap/single-cluster/rio-apps